# Наименование воркфлоу
name: CI/CD Pipeline Testing and Deploy for my simple project java

# Триггеры и ветки для старта воркфлоу
on:
  push:
    branches:
      - main  # Воркфлоу запускается при пуше в ветку main
  pull_request:
    branches:
      - main  # Воркфлоу запускается при создании пул-реквеста в ветку main

# Джобы или задачи для выполнения
jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}  # Запуск на разных операционных системах, указанных в матрице
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]  # Разные операционные системы для тестирования
        include:
          - os: macos-latest
            architecture: x64  # Архитектура x64 для macOS
          - os: macos-latest
            architecture: arm64  # Архитектура arm64 для macOS
    steps:
      # Шаг 1: Копирование кода из репозитория
      - name: Checkout code
        uses: actions/checkout@v3  # Используется action для копирования кода

      # Шаг 2: Установка JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3  # Используется action для установки Java
        with:
          java-version: '17'  # Версия Java
          distribution: 'adopt'  # Дистрибутив Java
          architecture: ${{ matrix.architecture }}  # Архитектура (из матрицы)

      # Шаг 3: Сборка проекта с помощью Maven
      - name: Build project
        run: mvn -B package  # Команда для сборки проекта

      # Шаг 4: Запуск тестов с помощью Maven
      - name: Run tests
        run: mvn -B test  # Команда для запуска тестов

  # Джоб для деплоя приложения
  fake-deploy:
    runs-on: ubuntu-latest
    needs: build-and-test
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Fake deploy step
        run: |
          echo "🚀 Deploying application..."
          echo "✅ Application successfully deployed (fake step just for deploy simulation)."