name: CI/CD Pipeline Testing and Deploy for my simple project java

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - os: macos-latest
            architecture: x64  # Intel
          - os: macos-latest
            architecture: arm64  # Apple Silicon
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          architecture: ${{ matrix.architecture }}

      - name: Build project
        run: mvn -B package

      - name: Run tests
        run: mvn -B test

  fake-deploy:
    runs-on: ubuntu-latest
    needs: build-and-test
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Fake deploy step
        run: |
          echo "🚀 Deploying application..."
          echo "✅ Application successfully deployed (fake step just for deploy simulation)."